var five = 5;
var ten = 10;
console.log("Test 1: five is equal to 5");
console.log(five == 5);
console.log("Test 2: ten is equal to 10");
console.log(ten == 10);
console.log("Test 3: five is lessthan 10");
console.log(five < 10);
console.log("Test 4: ten is greaterthan 5");
console.log(ten > 5);
console.log("Test 5: five is not equal to 10");
console.log(five !== 10);
console.log("Test 6: five is equal to 10");
console.log(five == 10);
console.log("Test 7: ten is equal to 5");
console.log(ten == 5);
console.log("Test 8: 10 is lessthan 5");
console.log(ten < 5);
console.log("Test 9: five is greaterthan 10");
console.log(five > 10);
console.log("Test 10: ten is not equal to 10");
console.log(ten !== 10);
